name = "WannierExcitonModel"
uuid = "b427a48a-3e32-43b5-a614-63ff4457e590"
authors = ["FanchenMeng mengfc011220@gmail.com"]
version = "0.1.0"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
